### ISSUE TITLE
Potential Bug: ERROR  ExchangeManager

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#103]
Hi @t0bst4r 

I'm getting a lot of the errors like the one below.

```
2024-06-19 17:09:37.693 ERROR  ExchangeManager      Cannot find a session for ID 52123
    at ExchangeManager.onMessage (file:///app/node_modules/@project-chip/matter.js/dist/esm/protocol/ExchangeManager.js:136:13)
    at file:///app/node_modules/@project-chip/matter.js/dist/esm/protocol/ExchangeManager.js:73:14
    at file:///app/node_modules/@project-chip/matter.js/dist/esm/net/UdpInterface.js:25:52
    at Socket.messageListener (file:///app/node_modules/@project-chip/matter-node.js/dist/esm/net/UdpChannelNode.js:101:7)
    at Socket.emit (node:events:517:28)
    at UDP.onMessage [as onmessage] (node:dgram:942:8)

```

**Comment by t0bst4r** [comment]
This should primarily happen when restarting Matterbridge. This happens when the paired device (e.g. alexa) still tries to connect using the previous session. It will get it after some minutes and those error logs stop. That’s a thing of `@project-chip/matter.js`. I am not sure if we can do anything about this.
