### ISSUE TITLE
[v1.2.0] Adding an AC climate control device causes errors

### ISSUE THREAD

**Issue by indiesaudi** [t0bst4r/matterbridge-home-assistant#105]
Getting this error when trying to start the plugin and it crashes in 1.2.0

[22:54:06.822] [Matterbridge] Added and registered bridged device (12/12) Bedroom AC (MA-heatcool) for plugin matterbridge-home-assistant 
file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261
          throw new ImplementationError(
                ^

ImplementationError: Attribute minLevel is optional and not initialized. To use it please initialize it first.
    at ClusterServer.result.<computed> [as setMinLevelAttribute] (file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261:17)
    at LevelControlAspect.update (file:///app/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:34:39)
    at ClimateDevice.updateState (file:///app/node_modules/matterbridge-home-assistant/lib/devices/home-assistant-device.js:21:26)
    at async HomeAssistantMatterAdapter.create (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:88:9)
    at async HomeAssistantMatterAdapter.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:42:13)
    at async HomeAssistantClient.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-client.js:50:13)

Node.js v18.20.3

**Comment by t0bst4r** [comment]
Yes, we already found that in #47.
I’ll close this one and let’s keep track in the other issue.
