### ISSUE TITLE
[Bug]: Empty devices page in the UI

### ISSUE THREAD

**Issue by genehand** [t0bst4r/matterbridge-home-assistant#215]
### What happened?

After upgrading, everything is still working with Alexa but the devices page in the matterbridge UI is empty.  I see the following error when I refresh.

### Relevant log output

```shell
Jul 24 16:34:12 chip matterbridge[160]: TypeError: clusterServer.getCurrentHueAttribute is not a function
Jul 24 16:34:12 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:3089:64
Jul 24 16:34:12 chip matterbridge[160]:     at Array.forEach (<anonymous>)
Jul 24 16:34:12 chip matterbridge[160]:     at Matterbridge.getClusterTextFromDevice (file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:3074:24)
Jul 24 16:34:12 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:2751:38
Jul 24 16:34:12 chip matterbridge[160]:     at Array.forEach (<anonymous>)
Jul 24 16:34:12 chip matterbridge[160]:     at file:///home/mb/node_modules/matterbridge/dist/matterbridge.js:2741:36
Jul 24 16:34:12 chip matterbridge[160]:     at Layer.handle [as handle_request] (/home/mb/node_modules/express/lib/router/layer.js:95:5)
Jul 24 16:34:12 chip matterbridge[160]:     at next (/home/mb/node_modules/express/lib/router/route.js:149:13)
Jul 24 16:34:12 chip matterbridge[160]:     at Route.dispatch (/home/mb/node_modules/express/lib/router/route.js:119:3)
Jul 24 16:34:12 chip matterbridge[160]:     at Layer.handle [as handle_request] (/home/mb/node_modules/express/lib/router/layer.js:95:5)
```

### Version

2.1.0

**Comment by genehand** [comment]
Looking closer at that error, this might be for the main matterbridge project? I'm using 1.4.0

**Comment by t0bst4r** [comment]
Seems to be a bug in the Matterbridge API. 
i‘ll keep this issue open for others to find it.

**Comment by t0bst4r** [comment]
Matterbridge `1.4.1` was released and I've upgraded to it. Could you please give it a try?

**Comment by cameronkelley** [comment]
Just tested latest and devices are now showing. Thanks!
