### ISSUE TITLE
[Bug]: Covers (garagedoors) reporting incorrect types

### ISSUE THREAD

**Issue by rexhoffman** [t0bst4r/matterbridge-home-assistant#232]
### What happened?

Matterserver is unpairable when a cover is exposed through matterbridge-homeassistant-plugin

### Your configuration

      MHA_CONFIG: |
        {
          "homeAssistant": {
            "url": "http://******:8123",
            "accessToken": "******",
            "matcher": {
              "includeDomains": ["lock", "cover"],
              "excludePatterns": ["media_player.*echo*", "cover.velux_internal_cover_venetian_blinds", "cover.velux_window_roof_window"]
            }
          }
        }

### Relevant log output

```shell
2024-07-28 20:47:05.882 ERROR  MatterServer         Failed to start node with storageKey Matterbridge: Device type MA-windowcovering (0x202) requires cluster server Identify(0x3) but it is not present on endpoint 2
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:224:17
    at Array.forEach (<anonymous>)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:221:42
    at Array.forEach (<anonymous>)
    at MatterbridgeDevice.verifyRequiredClusters (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:220:22)
    at InteractionEndpointStructure.verifyAndInitializeStructureElementsFromEndpoint (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:64:14)
    at InteractionEndpointStructure.initializeStructureFromEndpoints (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:56:12)
    at InteractionEndpointStructure.initializeStructureFromEndpoints (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:57:12)
    at InteractionEndpointStructure.initializeFromEndpoint (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:50:10)
    at CommissioningServer.advertise (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/CommissioningServer.js:331:28)
[20:47:05.884] [Matterbridge] Matter server started




after removing all but one cover, get this error:
 MatterServer         Failed to start node with storageKey Matterbridge: Device type MA-windowcovering (0x202) requires cluster server Identify(0x3) but it is not present on endpoint 3
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:224:17
    at Array.forEach (<anonymous>)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:221:42
    at Array.forEach (<anonymous>)
    at MatterbridgeDevice.verifyRequiredClusters (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Endpoint.js:220:22)
    at InteractionEndpointStructure.verifyAndInitializeStructureElementsFromEndpoint (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:64:14)
    at InteractionEndpointStructure.initializeStructureFromEndpoints (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:56:12)
[21:37:19.134] [Matterbridge] Matter server started 
    at InteractionEndpointStructure.initializeStructureFromEndpoints (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:57:12)
    at InteractionEndpointStructure.initializeFromEndpoint (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionEndpointStructure.js:50:10)
    at CommissioningServer.advertise (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/CommissioningServer.js:331:28)
```

### Version

2.3.0 plugin on 1.4.1 matterbridge

**Comment by t0bst4r** [comment]
I have added the identify cluster, as your error message says it’s required. 

Could you give it a try using `2.3.1` ?
Unfortunalety I cannot test covers myself…

I’ll  not be at home for the next three days, so I’ll not be able to do another fix before Thursday.

**Comment by Ultra-bob** [comment]
> Unfortunalety I cannot test covers myself…

You should be able to make a template cover using some dummy switches and sensors, it wouldn't be realistic but it should be enough to test if it pairs
https://www.home-assistant.io/integrations/cover.template/

**Comment by t0bst4r** [comment]
That’s a good hint!

But that wouldn’t have covered the NaN error others reported 😅

**Comment by rexhoffman** [comment]
After running for a while the my install finally detected the 3 devices with the latest version of the plugin, and started getting I think the same NaN error Ultra-bob got.
 
 ```
 Subscription 3601995858 for Session 52760: Error while sending initial data reports The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at toBigInt (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/Number.js:25:38)
    at DataWriter.writeUInt64 (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/DataWriter.js:32:54)
    at TlvCodec.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvCodec.js:312:27)
    at TlvByteArrayWriter.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvSchema.js:74:14)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:57:18
    at Array.forEach (<anonymous>)
    at AnySchema.encodeTlvInternal (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:37:15)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:22:51
    at Array.forEach (<anonymous>)
[19:06:10.874] [PluginManager] Configuring plugin matterbridge-home-assistant type DynamicPlatform 
[19:06:10.874] [HomeAssistantPlatform] The plugin doesn't override onConfigure. 
[19:06:10.874] [PluginManager] Configured plugin matterbridge-home-assistant type DynamicPlatform 
2024-07-29 19:06:13.213 ERROR  InteractionServer    Subscription 3601995859 for Session 52760: Error while sending initial data reports The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at toBigInt (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/Number.js:25:38)
    at DataWriter.writeUInt64 (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/DataWriter.js:32:54)
    at TlvCodec.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvCodec.js:312:27)
    at TlvByteArrayWriter.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvSchema.js:74:14)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:57:18
    at Array.forEach (<anonymous>)
    at AnySchema.encodeTlvInternal (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:37:15)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:22:51
    at Array.forEach (<anonymous>)
2024-07-29 19:06:25.170 ERROR  InteractionServer    Subscription 3601995860 for Session 52760: Error while sending initial data reports The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at toBigInt (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/Number.js:25:38)
    at DataWriter.writeUInt64 (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/DataWriter.js:32:54)
    at TlvCodec.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvCodec.js:312:27)
    at TlvByteArrayWriter.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvSchema.js:74:14)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:57:18
    at Array.forEach (<anonymous>)
    at AnySchema.encodeTlvInternal (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:37:15)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:22:51
    at Array.forEach (<anonymous>)
[19:06:40.890] [Matterbridge] Setting reachability to true for Matterbridge 
```

We can mark this one as a dup (your call)

**Comment by rexhoffman** [comment]
Matter bridge is running in docker - I tend to update the plugin in the UI, and restart via the UI.    My config is currently baked in my docker-compose so I've gone through the song-dance of updating multiple times when changing config.    Need to finally put the config in a file.

This is the second time I've noticed the matterbridge server taking a while to register the plugin upgrade and get back in to a good state.

**Comment by t0bst4r** [comment]
Yes, that’s a dup now. I’ll close this one. But could you please create another issue for the restart thing? I‘d like to investigate this. Please add as much details as possible 👍
