### ISSUE TITLE
[Bug]: NaN values in cover and fans causing failed pairing with google home

### ISSUE THREAD

**Issue by Ultra-bob** [t0bst4r/matterbridge-home-assistant#247]
### What happened?

When I add the cover or fan domains to matterbridge, I get an error in the logs and the pairing fails leaving all my devices unavailable in Google Home. The cover issue is likely caused by this attribute
![image](https://github.com/user-attachments/assets/a808b30b-64eb-4cd5-9ada-8f63d462ff02)
and the fans show up as NaN%
![image](https://github.com/user-attachments/assets/47ab82a8-644c-4cda-a3c7-4ba7d690d413)

### Relevant log output

```shell
matterbridge-1  | 2024-08-04 21:06:42.161 ERROR  InteractionServer    Subscription 4130290532 for Session 10497: Error while sending initial data reports The number NaN cannot be converted to a BigInt because it is not an integer
matterbridge-1  |     at BigInt (<anonymous>)
matterbridge-1  |     at toBigInt (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/Number.js:25:38)
matterbridge-1  |     at DataWriter.writeUInt64 (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/DataWriter.js:32:54)
matterbridge-1  |     at TlvCodec.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvCodec.js:312:27)
matterbridge-1  |     at TlvByteArrayWriter.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvSchema.js:74:14)
matterbridge-1  |     at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:57:18
matterbridge-1  |     at Array.forEach (<anonymous>)
matterbridge-1  |     at AnySchema.encodeTlvInternal (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:37:15)
matterbridge-1  |     at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:22:51
matterbridge-1  |     at Array.forEach (<anonymous>)
```

### Version

2.4.0

**Comment by Ultra-bob** [comment]
this was not fixed

**Comment by Ultra-bob** [comment]
nevermind it was fixed but now there's a new issue with lights
