### ISSUE TITLE
Feature Request: climate support

### ISSUE THREAD

**Issue by marc3k18** [t0bst4r/matterbridge-home-assistant#47]
Hello,

I trying to install zigbee2mqtt addon but im still having some error. Its only for testing purpose!

Thanka
![Screenshot_20240609-182558](https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/97817024/13da2a74-9ffb-4f0a-91f3-1f6a981a2ecc)

**Comment by t0bst4r** [comment]
I didn’t had the chance looking into this, singe there are some other bugs to fix before. 
Bur I am atill having this in mind.  😁

**Comment by marc3k18** [comment]
No worry! Thanks!

**Comment by t0bst4r** [comment]
I have implemented basic climate support, but have no way to test it since i have no climate device.
It is currently available in the next beta-release.

You can fetch it (via Docker) using `ghcr.io/t0bst4r/matterbridge-home-assistant/beta:1.1.0-beta88`.
Could you please give it a try and provide feedback?

**Comment by marc3k18** [comment]
Thanks for your work!

But Im not equipe to run docker. Im running HA on with HAOS.

Can you add this to the addon in beta?

**Comment by t0bst4r** [comment]
Okay, I am currently refactoring the release flow - again 😂

I’ll change it to **not** release beta versions at all, but immediately release everything as soon as possible to get direct feedback.
It‘ll be available with the addon latest end of this week.

**Comment by marc3k18** [comment]
Hey!

I just try the last update for the climate. It automaticly crash when I add a climate entity.

Node.js v18.20.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Matterbridge
 Populate your Home Assistant instance as Matter Bridge
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.3
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#############################
CURRENT CLIENT CONFIGURATION:
{
  "includeDomains": [],
  "includePatterns": [
    "light.gv_led_lumiere_ambiance_exterieur",
    "light.sl_lamp_c*",
    "switch.z2m_p_prise_exterieur",
    "switch.z2m_wv*",
    "climate.z2m*"
  ],
  "excludeDomains": [],
  "excludePatterns": []
}
#############################

> matterbridge
> matterbridge -add ./node_modules/matterbridge-home-assistant

[21:01:19.640] [Matterbridge] Created Matterbridge Plugin Directory: /root/Matterbridge 
[21:01:19.646] [Matterbridge] Matterbridge version 1.3.0 mode  running on Linux 6.6.33-haos linux x64 
[21:01:19.652] [Matterbridge] Plugin /app/node_modules/matterbridge-home-assistant/package.json already added to matterbridge 

> matterbridge
> matterbridge -bridge

[21:01:20.995] [Matterbridge] Matterbridge version 1.3.0 mode bridge running on Linux 6.6.33-haos linux x64 
[21:01:21.239] [Matterbridge] Loading plugin matterbridge-home-assistant type DynamicPlatform 
[21:01:21.241] [Matterbridge] WebSocketServer is listening on ws://10.18.0.250:8284 
[21:01:21.241] [Matterbridge] The frontend is listening on http://10.18.0.250:8283 
[21:01:21.323] [Matterbridge] Loaded plugin matterbridge-home-assistant type DynamicPlatform (entrypoint /app/node_modules/matterbridge-home-assistant/lib/index.js) 
[21:01:21.324] [Matterbridge] Starting plugin matterbridge-home-assistant type DynamicPlatform 
[21:01:21.324] [HomeAssistantPlatform] onStart called with reason: Matterbridge is starting 
[21:01:21.368] [Matterbridge] Started plugin matterbridge-home-assistant type DynamicPlatform 
[21:01:21.600] [Matterbridge] Added and registered bridged device (1/1) SL - LAMP - Chambre Principale (Local) (MA-onofflight) for plugin matterbridge-home-assistant 
[21:01:21.608] [Matterbridge] Added and registered bridged device (2/2) SL - LAMP - Cuisine (Local) (MA-onofflight) for plugin matterbridge-home-assistant 
[21:01:21.614] [Matterbridge] Added and registered bridged device (3/3) Z2M - T - Chambre Principale (MA-heatcool) for plugin matterbridge-home-assistant 
file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261
          throw new ImplementationError(
                ^

ImplementationError: Attribute minLevel is optional and not initialized. To use it please initialize it first.
    at ClusterServer.result.<computed> [as setMinLevelAttribute] (file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261:17)
    at LevelControlAspect.update (file:///app/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:34:39)
    at ClimateDevice.updateState (file:///app/node_modules/matterbridge-home-assistant/lib/devices/home-assistant-device.js:21:26)
    at async HomeAssistantMatterAdapter.create (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:88:9)
    at async HomeAssistantMatterAdapter.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:42:13)
    at async HomeAssistantClient.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-client.js:50:13)

Node.js v18.20.3
s6

**Comment by t0bst4r** [comment]
Thank you for the feedback. I’ll have a look into detail tomorrow. 
I just found a way to create a virtual devices using [generic-thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) and [hass-virtual](https://github.com/twrecked/hass-virtual/blob/master/README.md). 

If that works, I can test it locally and release more stable versions 🙂

**Comment by t0bst4r** [comment]
Virtual devices works!
Since the current implementation is just wrong, I need to re-implement the climate device.
I’ve disabled that device type for now in version 1.2.1

It’s not that easy. I need to understand how climates or thermostats work in matter.

**Comment by t0bst4r** [comment]
Due to limited time on my side and a slightly higher complexity in this kind of matter devices, i didn't have the possibility to finally implement that.
Sorry for postponing it even more.

**Comment by kaovilai** [comment]
Would be happy to help in any way.

I have a home kit enabled thermostat and HA + Google Home as Matter Controllers.

**Comment by t0bst4r** [comment]
Thanks for reminding me 😄 
I just had a quick look and it seemed that my initial implementation from months was just wrong 😆 

In general it will be possible, but I need to understand how climates work in home assistant.
Taking your previously posted attributes: 
```yaml 

hvac_modes:
  - heat
min_temp: 5
max_temp: 30
target_temp_step: 0.5
current_temperature: 21
temperature: 5
hvac_action: idle
friendly_name: Z2M - T - Chambre Garçons
supported_features: 385
```

- What features do they have and which of some are conditional? (Looking at `hvac_mode`). I can probably look that up in the Home Assistant documentation.
- `temperature` means the target temperature, right?
- Since there are also device able to do cooling, I don’t think setting the target temperature to min-temperature will turn off all devices. I’d expect to have a turn off service in home assistant, isn’t the one?
- How do those `auto` or `smart` modes work? Are they needed in the first step?

On the other hand I need to understand the matter api. For that I’d need to read a bit of the documentation as well.

I’ll try to get that done till the end of this week, but please forgive me if it takes longer, since I am doing that in my spare time besides family and full time work.

**Comment by tammeryousef1006** [comment]
thanks for following up

**Comment by kaovilai** [comment]
My thermostat on HA via HomeKit and in real life have three modes: cool, heat, off.
The same thermostat was earlier connected via [Smartthings](https://www.home-assistant.io/integrations/smartthings/) integration with [Honeywell Home](https://community.smartthings.com/t/honeywell-resideo-linked-services-help-request/263393) which also added fan control.

References:

> type string Required
> climate-hvac-modes
> 
> style string (Optional, default: icons)
> How the modes should be displayed. It can be either dropdown or icons.
> 
> hvac_modes list Required
> List of modes to show on the card. The list can contain auto, heat_cool, heat, cool, dry, fan_only, and off.

https://www.home-assistant.io/dashboards/features#climate-fan-modes

> type string Required
> climate-preset-modes
> 
> style string (Optional, default: dropdown)
> How the preset modes should be displayed. It can be either dropdown or icons.
> 
> preset_modes list Required
> List of preset modes to show on the card. The list can contain eco, away, boost, comfort, home, sleep, and activity or any other custom preset mode.

https://www.home-assistant.io/dashboards/features#climate-preset-modes

Other climate details:
https://www.home-assistant.io/integrations/climate

**Comment by tammeryousef1006** [comment]
here is mine

![4th ac](https://github.com/user-attachments/assets/9fef05be-ccf1-4fb4-a7de-7ff09320d74a)
![3rd ac](https://github.com/user-attachments/assets/2aa27c5b-b7a6-4f01-9a72-97e97586b54b)
![2nd ac](https://github.com/user-attachments/assets/14804537-d9e4-43a6-8fb0-86c4b3fe723e)
![1st ac](https://github.com/user-attachments/assets/20c29201-806c-4186-a1fd-f68f7ebd3c5e)

**Comment by t0bst4r** [comment]
okay, i've got a working version with my virtual heat-only device 😀 
I couldnt test cooling or combined devices. Additionally i did not implement "dry" or "fan_only", yet.
Just wanted to release early with limited features to get fast feedback.

**Comment by marc3k18** [comment]
All my device are heat only if it could help.

**Comment by t0bst4r** [comment]
yeah, it was just released as `2.7.0`. please give it a try.

**Comment by tammeryousef1006** [comment]
i did try and exposed 4 ac's , all appears at smartthings but not controlling cool nor heat

**Comment by t0bst4r** [comment]
Can you provide some details?

**Comment by tammeryousef1006** [comment]
i see controls yes and they dont do anything , I will upload photo

**Comment by tammeryousef1006** [comment]
![Screenshot_20240816_224207_SmartThings](https://github.com/user-attachments/assets/58fc8fb9-cc3a-4576-9d42-0db5e2a8cfd7)
![Screenshot_20240816_224158_SmartThings](https://github.com/user-attachments/assets/28790177-fc4a-492a-84e5-0a976d3e3451)

**Comment by t0bst4r** [comment]
Is it also not possible to set the mode to „cool“ or „heat“?
At the moment, auto is not implemented. 

Could you please enable debug logging and see if there are any logs?

**Comment by tammeryousef1006** [comment]
i can choose coot heat auto , but the icon keeps loading forever and no command goes to ac

**Comment by t0bst4r** [comment]
1. Yes, that’s probably the point. We cannot control the temperature without setting the mode to something other than off. 
I have added debug logs which show „change system mode from x to y“ when changing it. I’d like to see that in your logs. But therefore you need to enable debug log first. 

2. A different test: Can you try setting the mode in home assistant to (e.g.) heat? Does it change in smartthings as well then? Is it then possible to change the temperature?

**Comment by kaovilai** [comment]
```
2024-08-16 17:52:01.692 ERROR  InteractionServer    Error while handling write request from udp://fe80::a400:fb07:2700:1988%end0:5540 on session secure/5609 to MA-thermostat(0xb0)/Thermostat(0x201)/systemMode(0x1c): (136) Fixed attributes cannot be written
```

**Comment by t0bst4r** [comment]
Thank you! That is helpful. I’ll have a look at it later today

**Comment by t0bst4r** [comment]
That's interesting. Attributes in `matter.js` **can** be `FixedAttribute` or `WritableAttribute`.
If we try to change fixed attributes, we get the error message you have. On the other hand we can change writable attributes.

![Bildschirmfoto 2024-08-18 um 10 35 30](https://github.com/user-attachments/assets/a96f7e99-95ca-4393-a961-e923be01e047)

The only thing that makes me sceptical is `writeAcl: AccessLevel.Manage`. But there is no documentation available for that in `matter.js`.

---

Additionally I just had a look at the [list of supported devices and ecosystems](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#device-types-tested-on-various-ecosystems). Noone ever tested thermostats on smartthings and tuya.

**Comment by pkoutsovasilis** [comment]
> ```
> 2024-08-16 17:52:01.692 ERROR  InteractionServer    Error while handling write request from udp://fe80::a400:fb07:2700:1988%end0:5540 on session secure/5609 to MA-thermostat(0xb0)/Thermostat(0x201)/systemMode(0x1c): (136) Fixed attributes cannot be written
> ```

just providing some extra info; the same happens for me using google home, I can see my AC but I as soon as I try to change anything on Google home, such as mode, fan speed, temparature, nothing happens

**Comment by mclever** [comment]
And when trying to change the temp from google app the display changes from fahrenheit to Celsius
